name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy infrastructure?'
        required: true
        type: boolean

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Checkout the repository to access the Terraform configuration files
      - name: Checkout code
        uses: actions/checkout@v5

      # Configure AWS credentials for the workflow
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
    
      # Set up the Terraform CLI
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.1.7"

      # Initialize Terraform, which is required to access the remote state
      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform

      # Run the terraform destroy command to remove the infrastructure
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./Terraform
